### ISSUE TITLE
Push to @types repository

### ISSUE THREAD

**Issue by lukecwilliams** [nitintutlani/typed-graphql-relay#5]
Thought there would be no typings for graphql-relay, was very happy to find your repo!

Any reason not to push this to DefinitelyTyped so it can be found and improved by anyone, and installed easily with from @types/graphql-relay at the command line?  I can make the pull request but wanted to check with the author.

**Comment by intellix** [comment]
Do it before I do :)

**Comment by arvitaly** [comment]
https://www.npmjs.com/package/@types/graphql-relay
Done!
